Pin lemur-plugin-gcp-secretmanager dependency on googleapis-common-protos
Tasks are failing with:

```
{"log": "lemur.factory", "severity": "ERROR", "timestamp": "2022-04-20T13:55:34.202802", "message": "Failed to load plugin 'gcp_secretmanager_dest':\nTraceback (most recent call last):\n  File
\"/usr/src/app/.venv/lib/python3.7/site-packages/celery/app/utils.py\", line 373, in find_app\n    sym = symbol_by_name(app, imp=imp)\n  File
\"/usr/src/app/.venv/lib/python3.7/site-packages/celery/bin/base.py\", line 534, in symbol_by_name\n    return imports.symbol_by_name(name, imp=imp)\n  File
\"/usr/src/app/.venv/lib/python3.7/site-packages/kombu/utils/imports.py\", line 62, in symbol_by_name\n    return getattr(module, cls_name) if cls_name else module\nAttributeError: module
'lemur.common' has no attribute 'celery'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File
\"/usr/src/app/.venv/lib/python3.7/site-packages/lemur/factory.py\", line 230, in install_plugins\n    plugin = ep.load()\n  File
\"/usr/src/app/.venv/lib/python3.7/site-packages/pkg_resources/__init__.py\", line 2461, in load\n    self.require(*args, **kwargs)\n  File
\"/usr/src/app/.venv/lib/python3.7/site-packages/pkg_resources/__init__.py\", line 2484, in require\n    items = working_set.resolve(reqs, env, installer, extras=self.extras)\n  File
\"/usr/src/app/.venv/lib/python3.7/site-packages/pkg_resources/__init__.py\", line 792, in resolve\n    raise VersionConflict(dist,
req).with_context(dependent_req)\npkg_resources.ContextualVersionConflict: (googleapis-common-protos 1.53.0 (/usr/src/app/.venv/lib/python3.7/site-packages),
Requirement.parse('googleapis-common-protos[grpc]<2.0.0dev,>=1.56.0'), {'grpc-google-iam-v1'})\n\n"}
```

and:

```

Traceback (most recent call last):
  File "/usr/src/app/.venv/lib/python3.7/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/src/app/.venv/lib/python3.7/site-packages/lemur/common/celery.py", line 65, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/usr/src/app/.venv/lib/python3.7/site-packages/celery/app/trace.py", line 650, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/src/app/.venv/lib/python3.7/site-packages/lemur/common/celery.py", line 1312, in rotate_all_pending_endpoints
    [dest.plugin.verify(new_cert.name, dest.options) for dest in new_cert.destinations]
  File "/usr/src/app/.venv/lib/python3.7/site-packages/lemur/common/celery.py", line 1312, in <listcomp>
    [dest.plugin.verify(new_cert.name, dest.options) for dest in new_cert.destinations]
  File "/usr/src/app/.venv/lib/python3.7/site-packages/lemur/destinations/models.py", line 25, in plugin
    return plugins.get(self.plugin_name)
  File "/usr/src/app/.venv/lib/python3.7/site-packages/lemur/plugins/base/manager.py", line 44, in get
    raise KeyError(slug)
KeyError: 'gcp_secretmanager_destination'
```

We had issues with transitive dependencies moving to incompatible versions
so we pinned everything. googleapis-common-protos is a dependency of
google-api-core which allows for:

    googleapis-common-protos >= 1.6.0, < 2.0dev

Version 1.56.0 of googleapis-common-protos was released in March 2022
and is the latest at the time of writing. This is a newer version
than when we pinned to 1.53.0.

lemur-plugin-gcp-secretmanagers also depends on grpc-google-iam-v1==0.12.4
via google-cloud-secret-manager which requires googleapis-common-protos>=1.56.0.

So, to fix this we are pinning the version of googleapis-common-protos to 1.56.0.

This also pins lemur-plugin-gcp-secretmangers version of the dependency.