Correct slug for GcpSecretManagerDestination plugin
Tasks are failing with the error:

```

Traceback (most recent call last):
  File "/usr/src/app/.venv/lib/python3.7/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/src/app/.venv/lib/python3.7/site-packages/lemur/common/celery.py", line 65, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/usr/src/app/.venv/lib/python3.7/site-packages/celery/app/trace.py", line 650, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/src/app/.venv/lib/python3.7/site-packages/lemur/common/celery.py", line 1132, in certificate_check_destination
    uploaded = dest.plugin.verify(cert.name, dest.options)
  File "/usr/src/app/.venv/lib/python3.7/site-packages/lemur/destinations/models.py", line 25, in plugin
    return plugins.get(self.plugin_name)
  File "/usr/src/app/.venv/lib/python3.7/site-packages/lemur/plugins/base/manager.py", line 44, in get
    raise KeyError(slug)
KeyError: 'gcp_secretmanager_destination'
```

It looks like `gcp_secretmanager_destination` is an error and it should
be `gcp_secretmanager_dest` as that is used elsewhere.